import React from "react";
import Head from "next/head";
import { Header, Hero, Filter } from "@/components";
import { getProducts } from "@/api/products";
import { ProductT, ProductQueryParamsT } from "@/shared/types/product.type";

export default function Home() {
  const [products, setProducts] = React.useState<ProductT[]>([]);
  const [searchParams, setSearchParams] = React.useState<
    ProductQueryParamsT | undefined
  >();

  React.useEffect(() => {
    const fetchProducts = async () => {
      try {
        const res = await getProducts(searchParams);
        setProducts(res);
      } catch (error) {
        console.error(error);
      }
    };
    fetchProducts();
  }, [searchParams]);

  const handleFilter = (query: ProductQueryParamsT) => {
    setSearchParams(query);
  };

  return (
    <>
      <Head>
        <title>Sweet Apple Acres</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Filter onSearch={(query: ProductQueryParamsT) => handleFilter(query)} />
      <h1> Sweet Apple Acres</h1>
    </>
  );
}
